
name: Mac Nightly

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
    
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-12

    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
          submodules: 'true'
    
    - name: install python dependency
      run: pip install in_place  
      
    - name: generate nightly version number
      working-directory: build_scripts/msw
      run: python WriteNightlyVersionFiles.py  
     
    - name: Download wxWidgets
      run: 
        git clone --depth=1 --shallow-submodules  --recurse-submodules -b xlights_2022.13 https://github.com/xLightsSequencer/wxWidgets ../wxWidgets/

    - name: Build libraries
      working-directory: ../macOS/scripts/
      run: ./BuildLibsRelease.sh

    - name: Build wxWidgets
      working-directory: ../macOS/scripts/
      run: ./BuildLibsRelease.sh
      
    - name: Build xLights
      working-directory: ../macOS/scripts/
      run: ./BuildOSXRelease.sh  

    - name: Upload Installer
      uses: actions/upload-artifact@v2
      with:
        name: xLights_Installer
        path: '../macOS/scripts/**'
